apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: yash01er/api-gateway:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka

            - name: JWT_SECRET
              value: mysupersecurekeyformysafarsaathijwt1234567890abcdefABCDEF1234567890

            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin:9411/api/v2/spans