spring.application.name=payout-service

server.port=8098


spring.datasource.url=jdbc:mysql://mysql:3306/paypal_payoutdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=yash8252
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true


spring.kafka.bootstrap-servers=kafka:9092


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.auto-offset-reset=earliest


logging.level.org.springframework.kafka=INFO
logging.level.com.paypalclone.payout_service=DEBUG

# ======================
# ZIPKIN (Docker)
# ======================
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans