apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: yash01er/user-service:1.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8091

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/paypal_userdb

            - name: SPRING_DATASOURCE_USERNAME
              value: root

            - name: SPRING_DATASOURCE_PASSWORD
              value: yash8252

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://zipkin:9411/api/v2/spans